#ifndef DOGELIB_SCANCODES_H
#define DOGELIB_SCANCODES_H

#define SC_0                        SDL_SCANCODE_0
#define SC_1                        SDL_SCANCODE_1
#define SC_2                        SDL_SCANCODE_2
#define SC_3                        SDL_SCANCODE_3
#define SC_4                        SDL_SCANCODE_4
#define SC_5                        SDL_SCANCODE_5
#define SC_6                        SDL_SCANCODE_6
#define SC_7                        SDL_SCANCODE_7
#define SC_8                        SDL_SCANCODE_8
#define SC_9                        SDL_SCANCODE_9
#define SC_A                        SDL_SCANCODE_A
#define SC_AC_BACK                  SDL_SCANCODE_AC_BACK
#define SC_AC_BOOKMARKS             SDL_SCANCODE_AC_BOOKMARKS
#define SC_AC_FORWARD               SDL_SCANCODE_AC_FORWARD
#define SC_AC_HOME                  SDL_SCANCODE_AC_HOME
#define SC_AC_REFRESH               SDL_SCANCODE_AC_REFRESH
#define SC_AC_SEARCH                SDL_SCANCODE_AC_SEARCH
#define SC_AC_STOP                  SDL_SCANCODE_AC_STOP
#define SC_AGAIN                    SDL_SCANCODE_AGAIN
#define SC_ALTERASE                 SDL_SCANCODE_ALTERASE
#define SC_APOSTROPHE               SDL_SCANCODE_APOSTROPHE
#define SC_APPLICATION              SDL_SCANCODE_APPLICATION
#define SC_AUDIOMUTE                SDL_SCANCODE_AUDIOMUTE
#define SC_AUDIONEXT                SDL_SCANCODE_AUDIONEXT
#define SC_AUDIOPLAY                SDL_SCANCODE_AUDIOPLAY
#define SC_AUDIOPREV                SDL_SCANCODE_AUDIOPREV
#define SC_AUDIOSTOP                SDL_SCANCODE_AUDIOSTOP
#define SC_B                        SDL_SCANCODE_B
#define SC_BACKSLASH                SDL_SCANCODE_BACKSLASH
#define SC_BACKSPACE                SDL_SCANCODE_BACKSPACE
#define SC_BRIGHTNESSDOWN           SDL_SCANCODE_BRIGHTNESSDOWN
#define SC_BRIGHTNESSUP             SDL_SCANCODE_BRIGHTNESSUP
#define SC_C                        SDL_SCANCODE_C
#define SC_CALCULATOR               SDL_SCANCODE_CALCULATOR
#define SC_CANCEL                   SDL_SCANCODE_CANCEL
#define SC_CAPSLOCK                 SDL_SCANCODE_CAPSLOCK
#define SC_CLEAR                    SDL_SCANCODE_CLEAR
#define SC_CLEARAGAIN               SDL_SCANCODE_CLEARAGAIN
#define SC_COMMA                    SDL_SCANCODE_COMMA
#define SC_COMPUTER                 SDL_SCANCODE_COMPUTER
#define SC_COPY                     SDL_SCANCODE_COPY
#define SC_CRSEL                    SDL_SCANCODE_CRSEL
#define SC_CURRENCYSUBUNIT          SDL_SCANCODE_CURRENCYSUBUNIT
#define SC_CURRENCYUNIT             SDL_SCANCODE_CURRENCYUNIT
#define SC_CUT                      SDL_SCANCODE_CUT
#define SC_D                        SDL_SCANCODE_D
#define SC_DECIMALSEPARATOR         SDL_SCANCODE_DECIMALSEPARATOR
#define SC_DELETE                   SDL_SCANCODE_DELETE
#define SC_DISPLAYSWITCH            SDL_SCANCODE_DISPLAYSWITCH
#define SC_DOWN                     SDL_SCANCODE_DOWN
#define SC_E                        SDL_SCANCODE_E
#define SC_EJECT                    SDL_SCANCODE_EJECT
#define SC_END                      SDL_SCANCODE_END
#define SC_EQUALS                   SDL_SCANCODE_EQUALS
#define SC_ESCAPE                   SDL_SCANCODE_ESCAPE
#define SC_EXECUTE                  SDL_SCANCODE_EXECUTE
#define SC_EXSEL                    SDL_SCANCODE_EXSEL
#define SC_F                        SDL_SCANCODE_F
#define SC_F1                       SDL_SCANCODE_F1
#define SC_F10                      SDL_SCANCODE_F10
#define SC_F11                      SDL_SCANCODE_F11
#define SC_F12                      SDL_SCANCODE_F12
#define SC_F13                      SDL_SCANCODE_F13
#define SC_F14                      SDL_SCANCODE_F14
#define SC_F15                      SDL_SCANCODE_F15
#define SC_F16                      SDL_SCANCODE_F16
#define SC_F17                      SDL_SCANCODE_F17
#define SC_F18                      SDL_SCANCODE_F18
#define SC_F19                      SDL_SCANCODE_F19
#define SC_F2                       SDL_SCANCODE_F2
#define SC_F20                      SDL_SCANCODE_F20
#define SC_F21                      SDL_SCANCODE_F21
#define SC_F22                      SDL_SCANCODE_F22
#define SC_F23                      SDL_SCANCODE_F23
#define SC_F24                      SDL_SCANCODE_F24
#define SC_F3                       SDL_SCANCODE_F3
#define SC_F4                       SDL_SCANCODE_F4
#define SC_F5                       SDL_SCANCODE_F5
#define SC_F6                       SDL_SCANCODE_F6
#define SC_F7                       SDL_SCANCODE_F7
#define SC_F8                       SDL_SCANCODE_F8
#define SC_F9                       SDL_SCANCODE_F9
#define SC_FIND                     SDL_SCANCODE_FIND
#define SC_G                        SDL_SCANCODE_G
#define SC_GRAVE                    SDL_SCANCODE_GRAVE
#define SC_H                        SDL_SCANCODE_H
#define SC_HELP                     SDL_SCANCODE_HELP
#define SC_HOME                     SDL_SCANCODE_HOME
#define SC_I                        SDL_SCANCODE_I
#define SC_INSERT                   SDL_SCANCODE_INSERT
#define SC_J                        SDL_SCANCODE_J
#define SC_K                        SDL_SCANCODE_K
#define SC_KBDILLUMDOWN             SDL_SCANCODE_KBDILLUMDOWN
#define SC_KBDILLUMTOGGLE           SDL_SCANCODE_KBDILLUMTOGGLE
#define SC_KBDILLUMUP               SDL_SCANCODE_KBDILLUMUP
#define SC_KP_0                     SDL_SCANCODE_KP_0
#define SC_KP_00                    SDL_SCANCODE_KP_00
#define SC_KP_000                   SDL_SCANCODE_KP_000
#define SC_KP_1                     SDL_SCANCODE_KP_1
#define SC_KP_2                     SDL_SCANCODE_KP_2
#define SC_KP_3                     SDL_SCANCODE_KP_3
#define SC_KP_4                     SDL_SCANCODE_KP_4
#define SC_KP_5                     SDL_SCANCODE_KP_5
#define SC_KP_6                     SDL_SCANCODE_KP_6
#define SC_KP_7                     SDL_SCANCODE_KP_7
#define SC_KP_8                     SDL_SCANCODE_KP_8
#define SC_KP_9                     SDL_SCANCODE_KP_9
#define SC_KP_A                     SDL_SCANCODE_KP_A
#define SC_KP_AMPERSAND             SDL_SCANCODE_KP_AMPERSAND
#define SC_KP_AT                    SDL_SCANCODE_KP_AT
#define SC_KP_B                     SDL_SCANCODE_KP_B
#define SC_KP_BACKSPACE             SDL_SCANCODE_KP_BACKSPACE
#define SC_KP_BINARY                SDL_SCANCODE_KP_BINARY
#define SC_KP_C                     SDL_SCANCODE_KP_C
#define SC_KP_CLEAR                 SDL_SCANCODE_KP_CLEAR
#define SC_KP_CLEARENTRY            SDL_SCANCODE_KP_CLEARENTRY
#define SC_KP_COLON                 SDL_SCANCODE_KP_COLON
#define SC_KP_COMMA                 SDL_SCANCODE_KP_COMMA
#define SC_KP_D                     SDL_SCANCODE_KP_D
#define SC_KP_DBLAMPERSAND          SDL_SCANCODE_KP_DBLAMPERSAND
#define SC_KP_DECIMAL               SDL_SCANCODE_KP_DECIMAL
#define SC_KP_DIVIDE                SDL_SCANCODE_KP_DIVIDE
#define SC_KP_E                     SDL_SCANCODE_KP_E
#define SC_KP_ENTER                 SDL_SCANCODE_KP_ENTER
#define SC_KP_EQUALS                SDL_SCANCODE_KP_EQUALS
#define SC_KP_EQUALSAS400           SDL_SCANCODE_KP_EQUALSAS400
#define SC_KP_EXCLAM                SDL_SCANCODE_KP_EXCLAM
#define SC_KP_F                     SDL_SCANCODE_KP_F
#define SC_KP_GREATER               SDL_SCANCODE_KP_GREATER
#define SC_KP_HASH                  SDL_SCANCODE_KP_HASH
#define SC_KP_HEXADECIMAL           SDL_SCANCODE_KP_HEXADECIMAL
#define SC_KP_LEFTBRACE             SDL_SCANCODE_KP_LEFTBRACE
#define SC_KP_LEFTPAREN             SDL_SCANCODE_KP_LEFTPAREN
#define SC_KP_LESS                  SDL_SCANCODE_KP_LESS
#define SC_KP_MEMADD                SDL_SCANCODE_KP_MEMADD
#define SC_KP_MEMCLEAR              SDL_SCANCODE_KP_MEMCLEAR
#define SC_KP_MEMDIVIDE             SDL_SCANCODE_KP_MEMDIVIDE
#define SC_KP_MEMMULTIPLY           SDL_SCANCODE_KP_MEMMULTIPLY
#define SC_KP_MEMRECALL             SDL_SCANCODE_KP_MEMRECALL
#define SC_KP_MEMSTORE              SDL_SCANCODE_KP_MEMSTORE
#define SC_KP_MEMSUBTRACT           SDL_SCANCODE_KP_MEMSUBTRACT
#define SC_KP_MINUS                 SDL_SCANCODE_KP_MINUS
#define SC_KP_MULTIPLY              SDL_SCANCODE_KP_MULTIPLY
#define SC_KP_OCTAL                 SDL_SCANCODE_KP_OCTAL
#define SC_KP_PERCENT               SDL_SCANCODE_KP_PERCENT
#define SC_KP_PERIOD                SDL_SCANCODE_KP_PERIOD
#define SC_KP_PLUS                  SDL_SCANCODE_KP_PLUS
#define SC_KP_PLUSMINUS             SDL_SCANCODE_KP_PLUSMINUS
#define SC_KP_POWER                 SDL_SCANCODE_KP_POWER
#define SC_KP_RIGHTBRACE            SDL_SCANCODE_KP_RIGHTBRACE
#define SC_KP_RIGHTPAREN            SDL_SCANCODE_KP_RIGHTPAREN
#define SC_KP_SPACE                 SDL_SCANCODE_KP_SPACE
#define SC_KP_TAB                   SDL_SCANCODE_KP_TAB
#define SC_KP_VERTICALBAR           SDL_SCANCODE_KP_VERTICALBAR
#define SC_KP_XOR                   SDL_SCANCODE_KP_XOR
#define SC_L                        SDL_SCANCODE_L
#define SC_LALT                     SDL_SCANCODE_LALT
#define SC_LCTRL                    SDL_SCANCODE_LCTRL
#define SC_LEFT                     SDL_SCANCODE_LEFT
#define SC_LEFTBRACKET              SDL_SCANCODE_LEFTBRACKET
#define SC_LGUI                     SDL_SCANCODE_LGUI
#define SC_LSHIFT                   SDL_SCANCODE_LSHIFT
#define SC_M                        SDL_SCANCODE_M
#define SC_MAIL                     SDL_SCANCODE_MAIL
#define SC_MEDIASELECT              SDL_SCANCODE_MEDIASELECT
#define SC_MENU                     SDL_SCANCODE_MENU
#define SC_MINUS                    SDL_SCANCODE_MINUS
#define SC_MODE                     SDL_SCANCODE_MODE
#define SC_MUTE                     SDL_SCANCODE_MUTE
#define SC_N                        SDL_SCANCODE_N
#define SC_NUMLOCKCLEAR             SDL_SCANCODE_NUMLOCKCLEAR
#define SC_O                        SDL_SCANCODE_O
#define SC_OPER                     SDL_SCANCODE_OPER
#define SC_OUT                      SDL_SCANCODE_OUT
#define SC_P                        SDL_SCANCODE_P
#define SC_PAGEDOWN                 SDL_SCANCODE_PAGEDOWN
#define SC_PAGEUP                   SDL_SCANCODE_PAGEUP
#define SC_PASTE                    SDL_SCANCODE_PASTE
#define SC_PAUSE                    SDL_SCANCODE_PAUSE
#define SC_PERIOD                   SDL_SCANCODE_PERIOD
#define SC_POWER                    SDL_SCANCODE_POWER
#define SC_PRINTSCREEN              SDL_SCANCODE_PRINTSCREEN
#define SC_PRIOR                    SDL_SCANCODE_PRIOR
#define SC_Q                        SDL_SCANCODE_Q
#define SC_R                        SDL_SCANCODE_R
#define SC_RALT                     SDL_SCANCODE_RALT
#define SC_RCTRL                    SDL_SCANCODE_RCTRL
#define SC_RETURN                   SDL_SCANCODE_RETURN
#define SC_RETURN2                  SDL_SCANCODE_RETURN2
#define SC_RGUI                     SDL_SCANCODE_RGUI
#define SC_RIGHT                    SDL_SCANCODE_RIGHT
#define SC_RIGHTBRACKET             SDL_SCANCODE_RIGHTBRACKET
#define SC_RSHIFT                   SDL_SCANCODE_RSHIFT
#define SC_S                        SDL_SCANCODE_S
#define SC_SCROLLLOCK               SDL_SCANCODE_SCROLLLOCK
#define SC_SELECT                   SDL_SCANCODE_SELECT
#define SC_SEMICOLON                SDL_SCANCODE_SEMICOLON
#define SC_SEPARATOR                SDL_SCANCODE_SEPARATOR
#define SC_SLASH                    SDL_SCANCODE_SLASH
#define SC_SLEEP                    SDL_SCANCODE_SLEEP
#define SC_SPACE                    SDL_SCANCODE_SPACE
#define SC_STOP                     SDL_SCANCODE_STOP
#define SC_SYSREQ                   SDL_SCANCODE_SYSREQ
#define SC_T                        SDL_SCANCODE_T
#define SC_TAB                      SDL_SCANCODE_TAB
#define SC_THOUSANDSSEPARATOR       SDL_SCANCODE_THOUSANDSSEPARATOR
#define SC_U                        SDL_SCANCODE_U
#define SC_UNDO                     SDL_SCANCODE_UNDO
#define SC_UNKNOWN                  SDL_SCANCODE_UNKNOWN
#define SC_UP                       SDL_SCANCODE_UP
#define SC_V                        SDL_SCANCODE_V
#define SC_VOLUMEDOWN               SDL_SCANCODE_VOLUMEDOWN
#define SC_VOLUMEUP                 SDL_SCANCODE_VOLUMEUP
#define SC_W                        SDL_SCANCODE_W
#define SC_WWW                      SDL_SCANCODE_WWW
#define SC_X                        SDL_SCANCODE_X
#define SC_Y                        SDL_SCANCODE_Y
#define SC_Z                        SDL_SCANCODE_Z
#define SC_INTERNATIONAL1           SDL_SCANCODE_INTERNATIONAL1
#define SC_INTERNATIONAL2           SDL_SCANCODE_INTERNATIONAL2
#define SC_INTERNATIONAL3           SDL_SCANCODE_INTERNATIONAL3
#define SC_INTERNATIONAL4           SDL_SCANCODE_INTERNATIONAL4
#define SC_INTERNATIONAL5           SDL_SCANCODE_INTERNATIONAL5
#define SC_INTERNATIONAL6           SDL_SCANCODE_INTERNATIONAL6
#define SC_INTERNATIONAL7           SDL_SCANCODE_INTERNATIONAL7
#define SC_INTERNATIONAL8           SDL_SCANCODE_INTERNATIONAL8
#define SC_INTERNATIONAL9           SDL_SCANCODE_INTERNATIONAL9
#define SC_LANG1                    SDL_SCANCODE_LANG1
#define SC_LANG2                    SDL_SCANCODE_LANG2
#define SC_LANG3                    SDL_SCANCODE_LANG3
#define SC_LANG4                    SDL_SCANCODE_LANG4
#define SC_LANG5                    SDL_SCANCODE_LANG5
#define SC_LANG6                    SDL_SCANCODE_LANG6
#define SC_LANG7                    SDL_SCANCODE_LANG7
#define SC_LANG8                    SDL_SCANCODE_LANG8
#define SC_LANG9                    SDL_SCANCODE_LANG9
#define SC_LOCKINGCAPSLOCK          SDL_SCANCODE_LOCKINGCAPSLOCK
#define SC_LOCKINGNUMLOCK           SDL_SCANCODE_LOCKINGNUMLOCK
#define SC_LOCKINGSCROLLLOCK        SDL_SCANCODE_LOCKINGSCROLLLOCK
#define SC_NONUSBACKSLASH           SDL_SCANCODE_NONUSBACKSLASH
#define SC_BACKSLASH                SDL_SCANCODE_BACKSLASH
#define SC_NONUSHASH                SDL_SCANCODE_NONUSHASH

#endif /* end of include guard: DOGELIB_SCANCODES_H */
